# Generated by Django 5.2.7 on 2025-10-18 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity_per_day', models.PositiveIntegerField(default=20)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'name'], name='tours_produ_is_acti_946465_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('num_pax', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'date'], name='tours_booki_product_e6e043_idx'), models.Index(fields=['status'], name='tours_booki_status_7604a9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('num_pax__gte', 1)), name='num_pax_at_least_1')],
            },
        ),
    ]
